image: node:4.2.2

pages:
  cache:
    untracked: true
    paths:
    - node_modules/

  script:
  - npm install yarn gulp -g
  - yarn
  - gulp
  - mkdir public
  - mv dist/* public
  artifacts:
    paths:
    - public
  only:
  - master
