image: kkarczmarczyk/node-yarn:latest

pages:
  cache:
    untracked: true
    paths:
    - node_modules/

  script:
  - git config --global user.name "The Kollavarsham Team"
  - git config --global user.email "info@kollavarsham.org"
  - npm install gulp -g
  - yarn
  - gulp build-and-sync
  - mkdir public
  - mv dist/* public
  artifacts:
    paths:
    - public
  only:
  - master
